In [1]:
# import libraries
# to handle paths 
import os

# for data manipulation
import numpy as np
import pandas as pd

# for iterating
from itertools import product

# to display all columns
pd.set_option('display.max_columns', 10)

In [2]:
# define directories
data_folder = f"Data"
raw_folder = f"{data_folder}/raw/experiment_1"

# create directory
preprocessed_folder = f"{data_folder}/preprocessed/experiment_1"
os.makedirs(preprocessed_folder, exist_ok=True)

In [3]:
# define variables
suites = ['cec2013', 'cec2014', 'cec2015', 'cec2017', 'bbob']
algorithms = ["DE", "RealSpacePSO", "CMA"]
budget = 100000

# Target preparation

In [4]:
# load raw target data
target = pd.read_csv(f"{raw_folder}/performance_data.csv", index_col=0)
target.head(15)

,optimizer_name,optimizer_budget,benchmark_suite,fid,iid,f_opt,dimensions,function_evaluations,f_best
0,DE,100000,CEC2013,1,1,-1400.0,10,98327.0,-1399.999822
1,DE,100000,CEC2013,1,1,-1400.0,10,83418.0,-1397.565531
2,DE,100000,CEC2013,1,1,-1400.0,10,96597.0,-1399.529409
3,DE,100000,CEC2013,1,1,-1400.0,10,90473.0,-1399.842448
4,DE,100000,CEC2013,1,1,-1400.0,10,99745.0,-1399.685237
5,DE,100000,CEC2013,1,1,-1400.0,10,86820.0,-1399.804799
6,DE,100000,CEC2013,1,1,-1400.0,10,96680.0,-1399.729248
7,DE,100000,CEC2013,1,1,-1400.0,10,61177.0,-1395.332492
8,DE,100000,CEC2013,1,1,-1400.0,10,88784.0,-1399.912419
9,DE,100000,CEC2013,1,1,-1400.0,10,77293.0,-1399.190778
10,DE,100000,CEC2013,1,1,-1400.0,10,88299.0,-1399.827443
11,DE,100000,CEC2013,1,1,-1400.0,10,94401.0,-1399.976980
12,DE,100000,CEC2013,1,1,-1400.0,10,92605.0,-1399.349089
13,DE,100000,CEC2013,1,1,-1400.0,10,89022.0,-1399.922897
14,DE,100000,CEC2013,1,1,-1400.0,10,97082.0,-1399.996814

In [5]:
# preview data
target.shape

(19980, 9)

In [6]:
target.dtypes

optimizer_name           object
optimizer_budget          int64
benchmark_suite          object
fid                       int64
iid                       int64
f_opt                   float64
dimensions                int64
function_evaluations    float64
f_best                  float64
dtype: object

In [7]:
for column in ["optimizer_name", "optimizer_budget", "benchmark_suite", "dimensions"]:
    print(column)
    print(target[column].unique())
    print("\n")

optimizer_name
['DE' 'RealSpacePSO' 'CMA']


optimizer_budget
[100000]


benchmark_suite
['CEC2013' 'CEC2014' 'CEC2015' 'CEC2017' 'BBOB']


dimensions
[10]

In [8]:
# calculate precision 
target["precision"] = abs(target["f_opt"] - target["f_best"])
target.head(31)

,optimizer_name,optimizer_budget,benchmark_suite,fid,iid,f_opt,dimensions,function_evaluations,f_best,precision
0,DE,100000,CEC2013,1,1,-1400.0,10,98327.0,-1399.999822,0.000178
1,DE,100000,CEC2013,1,1,-1400.0,10,83418.0,-1397.565531,2.434469
2,DE,100000,CEC2013,1,1,-1400.0,10,96597.0,-1399.529409,0.470591
3,DE,100000,CEC2013,1,1,-1400.0,10,90473.0,-1399.842448,0.157552
4,DE,100000,CEC2013,1,1,-1400.0,10,99745.0,-1399.685237,0.314763
5,DE,100000,CEC2013,1,1,-1400.0,10,86820.0,-1399.804799,0.195201
6,DE,100000,CEC2013,1,1,-1400.0,10,96680.0,-1399.729248,0.270752
7,DE,100000,CEC2013,1,1,-1400.0,10,61177.0,-1395.332492,4.667508
8,DE,100000,CEC2013,1,1,-1400.0,10,88784.0,-1399.912419,0.087581
9,DE,100000,CEC2013,1,1,-1400.0,10,77293.0,-1399.190778,0.809222
10,DE,100000,CEC2013,1,1,-1400.0,10,88299.0,-1399.827443,0.172557
11,DE,100000,CEC2013,1,1,-1400.0,10,94401.0,-1399.976980,0.023020
12,DE,100000,CEC2013,1,1,-1400.0,10,92605.0,-1399.349089,0.650911
13,DE,100000,CEC2013,1,1,-1400.0,10,89022.0,-1399.922897,0.077103
14,DE,100000,CEC2013,1,1,-1400.0,10,97082.0,-1399.996814,0.003186
15,DE,100000,CEC2013,1,1,-1400.0,10,92681.0,-1399.687946,0.312054
16,DE,100000,CEC2013,1,1,-1400.0,10,99991.0,-1399.849965,0.150035
17,DE,100000,CEC2013,1,1,-1400.0,10,96008.0,-1399.969559,0.030441
18,DE,100000,CEC2013,1,1,-1400.0,10,77036.0,-1399.966777,0.033223
19,DE,100000,CEC2013,1,1,-1400.0,10,68824.0,-1399.934215,0.065785
20,DE,100000,CEC2013,1,1,-1400.0,10,99902.0,-1399.805642,0.194358
21,DE,100000,CEC2013,1,1,-1400.0,10,87511.0,-1399.993053,0.006947
22,DE,100000,CEC2013,1,1,-1400.0,10,99324.0,-1399.707040,0.292960
23,DE,100000,CEC2013,1,1,-1400.0,10,14608.0,-1397.096400,2.903600
24,DE,100000,CEC2013,1,1,-1400.0,10,99416.0,-1399.739475,0.260525
25,DE,100000,CEC2013,1,1,-1400.0,10,89220.0,-1399.999813,0.000187
26,DE,100000,CEC2013,1,1,-1400.0,10,82854.0,-1399.952192,0.047808
27,DE,100000,CEC2013,1,1,-1400.0,10,97265.0,-1399.999176,0.000824
28,DE,100000,CEC2013,1,1,-1400.0,10,59276.0,-1399.966639,0.033361
29,DE,100000,CEC2013,1,1,-1400.0,10,97927.0,-1399.935190,0.064810
0,DE,100000,CEC2013,2,1,-1300.0,10,97093.0,4379.951328,5679.951328

In [9]:
# aggregate runs with median
target = target.groupby(["optimizer_name", "benchmark_suite", "fid", "iid"])["precision"].median().reset_index()
target.head()

  optimizer_name benchmark_suite  fid  iid     precision
0            CMA            BBOB    1    1  1.675725e-08
1            CMA            BBOB    1    2  1.689847e-08
2            CMA            BBOB    1    3  1.986993e-08
3            CMA            BBOB    1    4  1.943977e-08
4            CMA            BBOB    1    5  2.301761e-08

In [10]:
# 30 runs * 3 algorithms * 5 suites * cal
target.shape

(666, 5)

In [11]:
# transform benchmark_suite column to match features column
target["benchmark_suite"] = target["benchmark_suite"].str.lower()
target

    optimizer_name benchmark_suite  fid  iid     precision
0              CMA            bbob    1    1  1.675725e-08
1              CMA            bbob    1    2  1.689847e-08
2              CMA            bbob    1    3  1.986993e-08
3              CMA            bbob    1    4  1.943977e-08
4              CMA            bbob    1    5  2.301761e-08
..             ...             ...  ...  ...           ...
661   RealSpacePSO         cec2017   25    1  4.456342e+02
662   RealSpacePSO         cec2017   26    1  3.471494e+02
663   RealSpacePSO         cec2017   27    1  4.032556e+02
664   RealSpacePSO         cec2017   28    1  5.948495e+02
665   RealSpacePSO         cec2017   29    1  3.091586e+02

[666 rows x 5 columns]

In [12]:
target.dtypes

optimizer_name      object
benchmark_suite     object
fid                  int64
iid                  int64
precision          float64
dtype: object

In [13]:
# rename columns to match features column names
target = target.rename(columns={"fid": "f_id", "iid": "i_id"})
target.head()

  optimizer_name benchmark_suite  f_id  i_id     precision
0            CMA            bbob     1     1  1.675725e-08
1            CMA            bbob     1     2  1.689847e-08
2            CMA            bbob     1     3  1.986993e-08
3            CMA            bbob     1     4  1.943977e-08
4            CMA            bbob     1     5  2.301761e-08

In [14]:
# check for nan
target.isnull().sum()

optimizer_name     0
benchmark_suite    0
f_id               0
i_id               0
precision          0
dtype: int64

In [14]:
# save target
target.to_csv(f"{preprocessed_folder}/target_preprocessed.csv", index=False)

# Features preparation

In [15]:
# load raw feature data
features = pd.read_csv(f"{raw_folder}/ela.csv", index_col=0)
features.head()

,run_id,suite,dimensions,fid,iid,...,pca.expl_var.cor_init,pca.expl_var_PC1.cov_x,pca.expl_var_PC1.cor_x,pca.expl_var_PC1.cov_init,pca.expl_var_PC1.cor_init
1,1,bbob,10,1,1,...,0.9091,0.1234,0.1234,0.9455,0.1621
2,2,bbob,10,1,1,...,0.9091,0.1244,0.1244,0.9436,0.1527
3,3,bbob,10,1,1,...,0.9091,0.1183,0.1183,0.9478,0.1586
4,4,bbob,10,1,1,...,0.9091,0.1172,0.1172,0.9490,0.1607
5,5,bbob,10,1,1,...,0.8182,0.1188,0.1188,0.9491,0.1598

In [16]:
# preview data
features.shape

(10170, 70)

In [17]:
features.dtypes

run_id                         int64
suite                         object
dimensions                     int64
fid                            int64
iid                            int64
                              ...
pca.expl_var.cor_init        float64
pca.expl_var_PC1.cov_x       float64
pca.expl_var_PC1.cor_x       float64
pca.expl_var_PC1.cov_init    float64
pca.expl_var_PC1.cor_init    float64
Length: 70, dtype: object

In [18]:
for column in ["suite", "dimensions"]:
    print(column)
    print(features[column].unique())
    print("\n")

suite
['bbob' 'cec2013' 'cec2014' 'cec2015' 'cec2017' 'all']


dimensions
[10]

In [19]:
# drop run_id and cluster
features = features.drop(["run_id", "cluster", "dimensions"], axis=1)
features.head()

,suite,fid,iid,disp.ratio_mean_02,disp.ratio_mean_05,...,pca.expl_var.cor_init,pca.expl_var_PC1.cov_x,pca.expl_var_PC1.cor_x,pca.expl_var_PC1.cov_init,pca.expl_var_PC1.cor_init
1,bbob,1,1,0.6454,0.7050,...,0.9091,0.1234,0.1234,0.9455,0.1621
2,bbob,1,1,0.6132,0.6832,...,0.9091,0.1244,0.1244,0.9436,0.1527
3,bbob,1,1,0.6083,0.6779,...,0.9091,0.1183,0.1183,0.9478,0.1586
4,bbob,1,1,0.6450,0.7061,...,0.9091,0.1172,0.1172,0.9490,0.1607
5,bbob,1,1,0.6263,0.6872,...,0.8182,0.1188,0.1188,0.9491,0.1598

In [20]:
# remove benchmark_suite == "all"
features = features[features["suite"] != "all"]
features.shape

(6630, 67)

In [21]:
# check for nan
features.columns[features.isna().any()].tolist()

['ic.eps.s']

In [22]:
# check for nan
features[features.isna().any(axis=1)][["suite", "fid", "iid"]].drop_duplicates()

        suite  fid  iid
3661  cec2013    3    1
3781  cec2013    7    1

In [23]:
# check for nan
features[features.isna().any(axis=1)].shape

(60, 67)

In [24]:
# remove nan 
features = features[~features.isna().any(axis=1)]

In [25]:
features.shape

(6570, 67)

In [26]:
# aggregate runs with median
features = features.groupby(["suite", "fid", "iid"]).median().reset_index()
features.head()

,suite,fid,iid,disp.ratio_mean_02,disp.ratio_mean_05,...,pca.expl_var.cor_init,pca.expl_var_PC1.cov_x,pca.expl_var_PC1.cor_x,pca.expl_var_PC1.cov_init,pca.expl_var_PC1.cor_init
0,bbob,1,1,0.62485,0.69035,...,0.8182,0.12020,0.12020,0.94845,0.16085
1,bbob,1,2,0.66480,0.72890,...,0.8182,0.11955,0.11955,0.97920,0.17540
2,bbob,1,3,0.66220,0.72970,...,0.8182,0.12045,0.12045,0.97665,0.17465
3,bbob,1,4,0.64655,0.71385,...,0.8182,0.11915,0.11915,0.96670,0.17005
4,bbob,1,5,0.63995,0.70860,...,0.8182,0.12035,0.12035,0.96695,0.16980

In [27]:
features.dtypes

suite                         object
fid                            int64
iid                            int64
disp.ratio_mean_02           float64
disp.ratio_mean_05           float64
                              ...
pca.expl_var.cor_init        float64
pca.expl_var_PC1.cov_x       float64
pca.expl_var_PC1.cor_x       float64
pca.expl_var_PC1.cov_init    float64
pca.expl_var_PC1.cor_init    float64
Length: 67, dtype: object

In [28]:
# rename columns
features = features.rename(columns={"suite": "benchmark_suite", "fid": "f_id", "iid": "i_id"})
features.head()

,benchmark_suite,f_id,i_id,disp.ratio_mean_02,disp.ratio_mean_05,...,pca.expl_var.cor_init,pca.expl_var_PC1.cov_x,pca.expl_var_PC1.cor_x,pca.expl_var_PC1.cov_init,pca.expl_var_PC1.cor_init
0,bbob,1,1,0.62485,0.69035,...,0.8182,0.12020,0.12020,0.94845,0.16085
1,bbob,1,2,0.66480,0.72890,...,0.8182,0.11955,0.11955,0.97920,0.17540
2,bbob,1,3,0.66220,0.72970,...,0.8182,0.12045,0.12045,0.97665,0.17465
3,bbob,1,4,0.64655,0.71385,...,0.8182,0.11915,0.11915,0.96670,0.17005
4,bbob,1,5,0.63995,0.70860,...,0.8182,0.12035,0.12035,0.96695,0.16980

In [29]:
features.shape

(219, 67)

In [30]:
# save features
features.to_csv(f"{preprocessed_folder}/ela_preprocessed.csv", index=False)

# Merge features and target

In [31]:
# merge on benchmark_suite, f_id, i_id
dataset = pd.merge(target, features, how='inner', on=["benchmark_suite", "f_id", "i_id"])
dataset.head()

,optimizer_name,benchmark_suite,f_id,i_id,precision,...,pca.expl_var.cor_init,pca.expl_var_PC1.cov_x,pca.expl_var_PC1.cor_x,pca.expl_var_PC1.cov_init,pca.expl_var_PC1.cor_init
0,CMA,bbob,1,1,1.675725e-08,...,0.8182,0.12020,0.12020,0.94845,0.16085
1,DE,bbob,1,1,5.714724e-02,...,0.8182,0.12020,0.12020,0.94845,0.16085
2,RealSpacePSO,bbob,1,1,1.575405e-08,...,0.8182,0.12020,0.12020,0.94845,0.16085
3,CMA,bbob,1,2,1.689847e-08,...,0.8182,0.11955,0.11955,0.97920,0.17540
4,DE,bbob,1,2,3.070117e-02,...,0.8182,0.11955,0.11955,0.97920,0.17540

In [32]:
dataset.shape

(654, 69)

In [33]:
dataset.dtypes

optimizer_name                object
benchmark_suite               object
f_id                           int64
i_id                           int64
precision                    float64
                              ...
pca.expl_var.cor_init        float64
pca.expl_var_PC1.cov_x       float64
pca.expl_var_PC1.cor_x       float64
pca.expl_var_PC1.cov_init    float64
pca.expl_var_PC1.cor_init    float64
Length: 69, dtype: object

In [34]:
# check for nans
dataset[dataset.isna().any(axis=1)]

Empty DataFrame
Columns: [optimizer_name, benchmark_suite, f_id, i_id, precision, disp.ratio_mean_02, disp.ratio_mean_05, disp.ratio_mean_10, disp.ratio_mean_25, disp.ratio_median_02, disp.ratio_median_05, disp.ratio_median_10, disp.ratio_median_25, disp.diff_mean_02, disp.diff_mean_05, disp.diff_mean_10, disp.diff_mean_25, disp.diff_median_02, disp.diff_median_05, disp.diff_median_10, disp.diff_median_25, ela_meta.lin_simple.adj_r2, ela_meta.lin_simple.intercept, ela_meta.lin_simple.coef.min, ela_meta.lin_simple.coef.max, ela_meta.lin_simple.coef.max_by_min, ela_meta.lin_w_interact.adj_r2, ela_meta.quad_simple.adj_r2, ela_meta.quad_simple.cond, ela_meta.quad_w_interact.adj_r2, ela_level.mmce_lda_10, ela_level.mmce_qda_10, ela_level.mmce_mda_10, ela_level.lda_qda_10, ela_level.lda_mda_10, ela_level.qda_mda_10, ela_level.mmce_lda_25, ela_level.mmce_qda_25, ela_level.mmce_mda_25, ela_level.lda_qda_25, ela_level.lda_mda_25, ela_level.qda_mda_25, ela_level.mmce_lda_50, ela_level.mmce_qda_50, ela_level.mmce_mda_50, ela_level.lda_qda_50, ela_level.lda_mda_50, ela_level.qda_mda_50, ela_distr.skewness, ela_distr.kurtosis, ela_distr.number_of_peaks, ic.h.max, ic.eps.s, ic.eps.max, ic.eps.ratio, ic.m0, nbc.nn_nb.sd_ratio, nbc.nn_nb.mean_ratio, nbc.nn_nb.cor, nbc.dist_ratio.coeff_var, nbc.nb_fitness.cor, pca.expl_var.cov_x, pca.expl_var.cor_x, pca.expl_var.cov_init, pca.expl_var.cor_init, pca.expl_var_PC1.cov_x, pca.expl_var_PC1.cor_x, pca.expl_var_PC1.cov_init, pca.expl_var_PC1.cor_init]
Index: []

[0 rows x 69 columns]

In [35]:
for column in ["optimizer_name", "benchmark_suite"]:
    print(column)
    print(dataset[column].unique())
    print("\n")

optimizer_name
['CMA' 'DE' 'RealSpacePSO']


benchmark_suite
['bbob' 'cec2013' 'cec2014' 'cec2015' 'cec2017']

# Create str datasets

In [36]:
for algorithm_name, benchmark_suite in product(algorithms, suites):
    print("\n")
    print(f"algorithm_name: {algorithm_name}, benchmark_suite: {benchmark_suite}")
    
    dataset_str = dataset[(dataset["optimizer_name"]==algorithm_name) & (dataset["benchmark_suite"]==benchmark_suite)]
    
    # drop 
    dataset_str = dataset_str.drop(["optimizer_name", "benchmark_suite"], axis=1)
    
    print(dataset_str.head(1))
    print(dataset_str.shape)
    
    # save
    title = f"suite={benchmark_suite}_algorithm_name={algorithm_name}_budget={budget}_dataset.csv"
    dataset_str.to_csv(f"{preprocessed_folder}/{title}", index=False)

algorithm_name: DE, benchmark_suite: cec2013
     f_id  i_id  precision  disp.ratio_mean_02  disp.ratio_mean_05  ...  \
361     1     1   0.153794              0.6411             0.70705  ...

     pca.expl_var.cor_init  pca.expl_var_PC1.cov_x  pca.expl_var_PC1.cor_x  \
361                 0.8182                 0.12065                 0.12065

     pca.expl_var_PC1.cov_init  pca.expl_var_PC1.cor_init
361                     0.9999                    0.16975

[1 rows x 67 columns]
(25, 67)


algorithm_name: DE, benchmark_suite: cec2014
     f_id  i_id  precision  disp.ratio_mean_02  disp.ratio_mean_05  ...  \
436     1     1   8.093189               0.855             0.87865  ...

     pca.expl_var.cor_init  pca.expl_var_PC1.cov_x  pca.expl_var_PC1.cor_x  \
436                 0.8182                  0.1212                  0.1212

     pca.expl_var_PC1.cov_init  pca.expl_var_PC1.cor_init
436                        1.0                    0.16475

[1 rows x 67 columns]
(30, 67)


algorithm_name: DE, benchmark_suite: cec2015
     f_id  i_id  precision  disp.ratio_mean_02  disp.ratio_mean_05  ...  \
526     1     1   52.35837             0.87035             0.89575  ...

     pca.expl_var.cor_init  pca.expl_var_PC1.cov_x  pca.expl_var_PC1.cor_x  \
526                 0.9091                 0.11955                 0.11955

     pca.expl_var_PC1.cov_init  pca.expl_var_PC1.cor_init
526                        1.0                     0.1513

[1 rows x 67 columns]
(15, 67)


algorithm_name: DE, benchmark_suite: cec2017
     f_id  i_id  precision  disp.ratio_mean_02  disp.ratio_mean_05  ...  \
571     1     1   2.493615             0.69315             0.74875  ...

     pca.expl_var.cor_init  pca.expl_var_PC1.cov_x  pca.expl_var_PC1.cor_x  \
571                 0.8182                 0.12085                 0.12085

     pca.expl_var_PC1.cov_init  pca.expl_var_PC1.cor_init
571                        1.0                    0.16635

[1 rows x 67 columns]
(28, 67)


algorithm_name: DE, benchmark_suite: bbob
   f_id  i_id  precision  disp.ratio_mean_02  disp.ratio_mean_05  ...  \
1     1     1   0.057147             0.62485             0.69035  ...

   pca.expl_var.cor_init  pca.expl_var_PC1.cov_x  pca.expl_var_PC1.cor_x  \
1                 0.8182                  0.1202                  0.1202

   pca.expl_var_PC1.cov_init  pca.expl_var_PC1.cor_init
1                    0.94845                    0.16085

[1 rows x 67 columns]
(120, 67)


algorithm_name: RealSpacePSO, benchmark_suite: cec2013
     f_id  i_id     precision  disp.ratio_mean_02  disp.ratio_mean_05  ...  \
362     1     1  1.119895e-08              0.6411             0.70705  ...

     pca.expl_var.cor_init  pca.expl_var_PC1.cov_x  pca.expl_var_PC1.cor_x  \
362                 0.8182                 0.12065                 0.12065

     pca.expl_var_PC1.cov_init  pca.expl_var_PC1.cor_init
362                     0.9999                    0.16975

[1 rows x 67 columns]
(25, 67)


algorithm_name: RealSpacePSO, benchmark_suite: cec2014
     f_id  i_id    precision  disp.ratio_mean_02  disp.ratio_mean_05  ...  \
437     1     1  2448.376711               0.855             0.87865  ...

     pca.expl_var.cor_init  pca.expl_var_PC1.cov_x  pca.expl_var_PC1.cor_x  \
437                 0.8182                  0.1212                  0.1212

     pca.expl_var_PC1.cov_init  pca.expl_var_PC1.cor_init
437                        1.0                    0.16475

[1 rows x 67 columns]
(30, 67)


algorithm_name: RealSpacePSO, benchmark_suite: cec2015
     f_id  i_id    precision  disp.ratio_mean_02  disp.ratio_mean_05  ...  \
527     1     1  7218.929331             0.87035             0.89575  ...

     pca.expl_var.cor_init  pca.expl_var_PC1.cov_x  pca.expl_var_PC1.cor_x  \
527                 0.9091                 0.11955                 0.11955

     pca.expl_var_PC1.cov_init  pca.expl_var_PC1.cor_init
527                        1.0                     0.1513

[1 rows x 67 columns]
(15, 67)


algorithm_name: RealSpacePSO, benchmark_suite: cec2017
     f_id  i_id   precision  disp.ratio_mean_02  disp.ratio_mean_05  ...  \
572     1     1  2771.81086             0.69315             0.74875  ...

     pca.expl_var.cor_init  pca.expl_var_PC1.cov_x  pca.expl_var_PC1.cor_x  \
572                 0.8182                 0.12085                 0.12085

     pca.expl_var_PC1.cov_init  pca.expl_var_PC1.cor_init
572                        1.0                    0.16635

[1 rows x 67 columns]
(28, 67)


algorithm_name: RealSpacePSO, benchmark_suite: bbob
   f_id  i_id     precision  disp.ratio_mean_02  disp.ratio_mean_05  ...  \
2     1     1  1.575405e-08             0.62485             0.69035  ...

   pca.expl_var.cor_init  pca.expl_var_PC1.cov_x  pca.expl_var_PC1.cor_x  \
2                 0.8182                  0.1202                  0.1202

   pca.expl_var_PC1.cov_init  pca.expl_var_PC1.cor_init
2                    0.94845                    0.16085

[1 rows x 67 columns]
(120, 67)


algorithm_name: CMA, benchmark_suite: cec2013
     f_id  i_id     precision  disp.ratio_mean_02  disp.ratio_mean_05  ...  \
360     1     1  9.658606e-09              0.6411             0.70705  ...

     pca.expl_var.cor_init  pca.expl_var_PC1.cov_x  pca.expl_var_PC1.cor_x  \
360                 0.8182                 0.12065                 0.12065

     pca.expl_var_PC1.cov_init  pca.expl_var_PC1.cor_init
360                     0.9999                    0.16975

[1 rows x 67 columns]
(25, 67)


algorithm_name: CMA, benchmark_suite: cec2014
     f_id  i_id     precision  disp.ratio_mean_02  disp.ratio_mean_05  ...  \
435     1     1  1.199598e-08               0.855             0.87865  ...

     pca.expl_var.cor_init  pca.expl_var_PC1.cov_x  pca.expl_var_PC1.cor_x  \
435                 0.8182                  0.1212                  0.1212

     pca.expl_var_PC1.cov_init  pca.expl_var_PC1.cor_init
435                        1.0                    0.16475

[1 rows x 67 columns]
(30, 67)


algorithm_name: CMA, benchmark_suite: cec2015
     f_id  i_id     precision  disp.ratio_mean_02  disp.ratio_mean_05  ...  \
525     1     1  1.277384e-08             0.87035             0.89575  ...

     pca.expl_var.cor_init  pca.expl_var_PC1.cov_x  pca.expl_var_PC1.cor_x  \
525                 0.9091                 0.11955                 0.11955

     pca.expl_var_PC1.cov_init  pca.expl_var_PC1.cor_init
525                        1.0                     0.1513

[1 rows x 67 columns]
(15, 67)


algorithm_name: CMA, benchmark_suite: cec2017
     f_id  i_id     precision  disp.ratio_mean_02  disp.ratio_mean_05  ...  \
570     1     1  1.111103e-08             0.69315             0.74875  ...

     pca.expl_var.cor_init  pca.expl_var_PC1.cov_x  pca.expl_var_PC1.cor_x  \
570                 0.8182                 0.12085                 0.12085

     pca.expl_var_PC1.cov_init  pca.expl_var_PC1.cor_init
570                        1.0                    0.16635

[1 rows x 67 columns]
(28, 67)


algorithm_name: CMA, benchmark_suite: bbob
   f_id  i_id     precision  disp.ratio_mean_02  disp.ratio_mean_05  ...  \
0     1     1  1.675725e-08             0.62485             0.69035  ...

   pca.expl_var.cor_init  pca.expl_var_PC1.cov_x  pca.expl_var_PC1.cor_x  \
0                 0.8182                  0.1202                  0.1202

   pca.expl_var_PC1.cov_init  pca.expl_var_PC1.cor_init
0                    0.94845                    0.16085

[1 rows x 67 columns]
(120, 67)